apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ template "fullname" . }}
spec:
  tls:
  - hosts: 
      - dynamodb.local.bricerising.com
    secretName: dynamodb.local.bricerising.com
  rules:
  - host: dynamodb.local.bricerising.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "fullname" . }}
              port:
                number: 8000

---
kind: KongIngress
apiVersion: configuration.konghq.com/v1
metadata:
  annotations:
    kubernetes.io/ingress.class: "kong"
  name: timeout-kong-ingress
proxy:
  protocol: http
  connect_timeout: 360000
  read_timeout: 360000
  write_timeout: 360000
