apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "fullname" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
